### ISSUE TITLE
implementar opções -v e -c

### ISSUE THREAD

**Issue by luisa-maria1111** [FlyHigh1111/SOPE#10]

**Comment by pmoreira01** [comment]
Ambas as opçoes já funcionam.
Falta fazer print das permissões ( sem ser em octal )

**Comment by pmoreira01** [comment]
Feito :smiley:

**Comment by luisa-maria1111** [comment]
Embora as permissões alterem corretamente, não mostra no ecrã corretamente.

**Comment by pmoreira01** [comment]
O erro apareceu devido a usar o xmod num diretorio, que o nosso programa ainda não suporta.
Mas mudei algumas cenas, que devem estar melhores.

**Comment by luisa-maria1111** [comment]
Eu vou fazer com que permita alterar permissoes dos diretorios e depois fazes com que apareça bem ignorando o 'd' i guess
