### ISSUE TITLE
enunciado "Tratamento de sinais" só com SIGINT para já

### ISSUE THREAD

**Issue by luisa-maria1111** [FlyHigh1111/SOPE#8]
enunciado "Tratamento de sinais" ainda antes de tratar da recursividade, talvez pôr um while(1) para dar tempo para fazer CTRL-C, passo 3 do plano de trabalho do enunciado

**Comment by luisa-maria1111** [comment]
@pipe-01 Quando pergunta a primeira vez exit or continue, e eu respondo continue. Depois fica à espera de input. Faço CTRL-C outra vez (da segunda vez) e dá "error, please enter a valid character."

**Comment by pipe-01** [comment]
sim eu ja tinha reparado nisso! eu nao sei é se fica à espera de input ou retorna ao ciclo infinito @luisa-maria1111

**Comment by luisa-maria1111** [comment]
hmm, não sei, mas tenta pôr um print no ciclo infinito e descobres. 
Outra coisa, podes pôr o args como variável global se quiseres (na aula de quarta perguntamos ao stor uma alternativa)

**Comment by luisa-maria1111** [comment]
@pipe-01 agora podes tentar com a recursividade. Se precisares adiciona mais ficherios e diretórios para dar tempo para fazer CTRL-C ou então metes um sleep por ali.
